steps:
    # Step 1: Build the Docker image using .env.production
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '--build-arg'
          - 'ENV=production'
          - '-t'
          - 'gcr.io/$PROJECT_ID/blogora-api:$COMMIT_SHA'
          - '-t'
          - 'gcr.io/$PROJECT_ID/blogora-api:latest'
          - '.'

    # Step 2: Push the Docker image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/blogora-api:$COMMIT_SHA']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/blogora-api:latest']

    # Step 3: Deploy to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - 'blogora-api'
          - '--image'
          - 'gcr.io/$PROJECT_ID/blogora-api:$COMMIT_SHA'
          - '--region'
          - '${_DEPLOY_REGION}'
          - '--platform'
          - 'managed'
          - '--allow-unauthenticated'
          - '--port'
          - '8080'
          - '--memory'
          - '512Mi'
          - '--cpu'
          - '1'
          - '--min-instances'
          - '0'
          - '--max-instances'
          - '10'

# Define substitutions for Cloud Run configuration
substitutions:
    _DEPLOY_REGION: 'asia-south1'

# Build timeout
timeout: '1200s'

# Build options
options:
    logging: CLOUD_LOGGING_ONLY

# Store images in Container Registry
images:
    - 'gcr.io/$PROJECT_ID/blogora-api:$COMMIT_SHA'
    - 'gcr.io/$PROJECT_ID/blogora-api:latest'
